### ISSUE TITLE
Album export on synology nas

### ISSUE THREAD

**Issue by grandmastermarco** [Caleb9/SynologyPhotosAlbumList#1]
Hi! Any chance you can help me out and point me in a direction on how to modify your code?
I am trying to export an album to a new directory by executing a script on the synology itself.
Your code looks promising. Thanks in advance
Eg. Album named ‚example‘ -> export / duplicate all photos to new directory ‚/home/example‘

**Comment by Caleb9** [comment]
Hi @grandmastermarco.

I think what you want to do is the same thing that initially pushed me to write this code, but I didn't get to implement the full workflow.

I guess there's several ways to go about it, but right off the bat it might not always work if some of the photos in the album are stored in another user's _Personal Space_ and your user doesn't have access to it. But let's ignore that and assume you have access to everything for the sake of what follows.

First question is if you wish to copy the photos to

1. another _folder_ controlled by Photos, i.e. one located (by default) under `/volume1/photo` (_Shared Space_) or `/volume1/homes/{your user name}/Photos` (_Personal Space_), or
2. any arbitrary folder on your NAS

## Case 1

In case 1 you could utilize Photos API, since it is possible to copy files between folders using the browser client:
![image](https://user-images.githubusercontent.com/7767011/205003851-ab34cab9-9bef-41f5-b012-51ceb4094b2b.png)

(It seems that you can only copy between the same space - Personal or Shared - but not from one to another.)

As you maybe know the API of Synology Photos is undocumented, but reverse engineering what the browser app is doing when you copy files, it sends a POST request with the `copy` method of `SYNO.Foto.BackgroundTask.File` API (for Personal space, and probably `SYNO.FotoTeam.BackgroundTask.File` for Shared). This method takes copied photo ID and target folder ID as parameters. Here's an example of the request's payload: `api=SYNO.Foto.BackgroundTask.File&method=copy&version=1&target_folder_id=2098&item_id=%5B62815%5D&folder_id=%5B%5D&action=%22skip%22`. There's `item_id` and `target_folder_id` there - I am not sure what `folder_id` is right now.

My code [already queries for IDs](https://github.com/Caleb9/SynologyPhotosAlbumList/blob/4c6e59977e8512e3b7049616ad1acc1c5ca40808/SynologyPhotosAlbumList/PhotosApi.fs#L34) of photos in an Album, so you have that part almost ready. Then you'd need to discover the ID of the target folder (the easiest would probably be inspecting the network traffic in the browser when listing that folder in Photos browser client), and for each photo construct that POST `copy` request and send it to the API - it's probably also possible to do that in bulks (one request to copy multiple photos) but we'd need to investigate further.

As for modifying the code you could copy and modify the [ListAlbumCommand.fs](https://github.com/Caleb9/SynologyPhotosAlbumList/blob/main/SynologyPhotosAlbumList/ListAlbumCommand.fs) and work from there.

## Case 2

To copy to any folder you'd probably need to have some script executed on the NAS itself in SSH session. I imagine using my code to generate list of photos in an album, and then processing that list to prepend the paths with fully qualified paths (i.e. including `/volume1/...` and so on), and then execute regular `cp` on them. You could do that in bash or python I guess. Would be more one-time solution but could be easier to implement, as you wouldn't have to use the Photos API at all.


Let me know if that helps, and if you get anywhere, would be great to hear how things went. :) If I get time I might add this functionality to my code someday, since as I said it is also something I would find useful for reorganizing my collection.

**Comment by grandmastermarco** [comment]
thank you so much for the quick and very detailed reply!
i am looking into case 2.
i have trouble executing your scripts on my synology nas in SSH. i have NET 6.0 installed from synocommunity, but executing dotnet --run --help gives following error.
"could not execute because the application was not found or a compatible .NET SDK ist not installed.

which parts of your codes can i extract to simly execute in task scheduler as bash?
i will try to work on the code and report back with results.

thanks in advance.

**Comment by Caleb9** [comment]
You're welcome :). I don't have .NET SDK on my NAS so can't be sure it will work, but your command looks wrong, i.e. it should be `dotnet run -- --help`.

Also, you don't need to execute this on the NAS itself, the communication is happening via HTTP, so you could install .NET SDK on your PC and run it from there too. If you can open Synology Photos in your browser, you can use this app from the same machine as well.

**Comment by grandmastermarco** [comment]
after tinkering abit with the code, sadly i cannot put your code to work yet.
the dotnet command finally works, but sadly puts out an error.

//HTTPS WITHOUT PORT
dotnet run --project ~/SynologyPhotosAlbumList -- list XXX -a https://XXX -u XXX -p XXX
-> Invalid HTTP response MethodNotAllowed: Not Allowed

//HTTPS WITH PORT
dotnet run --project ~/SynologyPhotosAlbumList -- list XXX -a https://XXX:5001 -u XXX -p XXX
-> Invalid HTTP response Forbidden: Forbidden

//HTTP WITH PORT
dotnet run --project ~/SynologyPhotosAlbumList -- list XXX -a http://XXX -u XXX:5000 -p XXX
-> Invalid HTTP response Forbidden: Forbidden


i am accessing my NAS through SSL / https, and i have a proper certificate for it.

Any chance of debugging? can i set a verbose flag somewhere for additional info?
thank you so much once again

**Comment by Caleb9** [comment]
Hmm I'll think of it more tomorrow, but for now:
1. Do you have Synology Photos updated?
2. You don't need the 5000 or 5001 port I think - that's only to access DSM's Web UI. Did you try HTTP without port? You could also try by IP address maybe?
3. Do you have 2FA enabled for your user account? If so, you need one more parameter `-o 123456` where 123456 is your code from authenticator app.
4. Right now there's no verbose flag or anything, but since you're compiling the code anyway, you can try to open and run it from Visual Studio, VS Code or JetBrains Rider with debugger attached.

One last thing, does Control Panel -> Login Portal -> Applications look like this on your NAS?
![image](https://user-images.githubusercontent.com/7767011/205159708-93ba008a-03fb-4697-a041-396b908255ab.png)

**Comment by Caleb9** [comment]
@grandmastermarco I get "MethodNotAllowed" when something's not right with the URL. Are you able to open Synology Photos using `https://XXX/photo` in your browser?

**Comment by grandmastermarco** [comment]
Thank you sk much for the very detailed troubleshooting! I will report back soon with all the answers to your suggestions. Just one quick hint for me: can you give me an example on how you put the url in dotnet run command? Maybe this will fix the issues...
E.g. http://192.168.178.2
Or http://192.168.178.2/
Or http://192.168.178.2:5000/
Or http://192.168.178.2/photos
...
Thank you so much once again

**Comment by grandmastermarco** [comment]
> One last thing, does Control Panel -> Login Portal -> Applications look like this on your NAS?

Thank you so much for the very detailed troubleshooting! 
It works! I had some time to at least go through your points and finally figured out the problem.
Applications portal (by default?) does not have the photos alias for photos application (at least on 2 NASes I tested?.
I modified it and now the code works...
Now I will try to figure out how to export the album.
I will report back 
Thanks so much!

**Comment by Caleb9** [comment]
Nice! I overlooked the fact that the alias is not there by default. I was implementing the thing until "it worked on my machine" ;), so the "photo" part of URL path is currently hard-coded, as I didn't remember setting that up in the past. I should look into fixing that at some point, thanks for helping me discover the problem.

**Comment by Caleb9** [comment]
I pushed a commit containing fix for the alias requirement - it is no longer needed to set it up. :)

**Comment by Caleb9** [comment]
@grandmastermarco I pushed a commit that adds an "export" command to do what you wanted in the app. It fixes some bugs as well. It is still not perfect, as it only schedules copying of photos on the NAS but doesn't output the results (success or failure) to the console. So it's necessary to check the web interface, but it works nevertheless. Let me know if you get a chance to try it out :).

**Comment by grandmastermarco** [comment]
@Caleb9 thank you so much for the great update!!
