### ISSUE TITLE
"Folder XXX not found in personal space"

### ISSUE THREAD

**Issue by grandmastermarco** [Caleb9/SynologyPhotosAlbumList#2]
hi @Caleb9 
thanks again for the great update.

i am trying to utilize the new export function of your script.
i tried pretty much all possible folder formats, sadly i always get an error:
"Folder XX not found in personal space"

for example i create a directory "test" under the users home directory (home/test/)
using the export function, i define the directory as "/test".

i am running the script from a remote device, not the SynologyNAS itself. 
connection ist fine, list command of the same album shows expected result.

am i doing it wrong?

one additional feature request:
any chance i would be able to specify a directory in another accesible home directory
(homes/userB/test) instead of home directory of user A? or just any other accesible path on the NAS itself?

**Comment by grandmastermarco** [comment]
Just to clarify my usecase:
I have a shared album between 2 users. both users can add photos from their personal space aswell as shared space.

With your script listing the album by logging in User A echos all pictures of User A personal space and shared space, and echos errors for User B added pictures.

Therefore i will execute the script twice, one time logging in user A, on time logging in user B. the whole album should then be exported to a directory which is accesible by both users (as i understand by your readme, duplicates will be skipped - in this case all pictures from shared space).

Do you think this is the right approach for my usecase?
Thank you so much in advance.

**Comment by Caleb9** [comment]
@grandmastermarco Currently, what you're trying to do is not really possible. The reason is that your `/home/test` folder is not a folder accessible by Synology Photos. To make it work the folder would have to be in `/home/Photos/test`. Best way to create one is via the Photos interface itself (although you can try to do it via File Station as well):

![image](https://user-images.githubusercontent.com/7767011/218254356-cf2c0467-7b1f-4161-b19f-ecb3d5ed2a2e.png)

And then use `/test` as the parameter for the app.

Because the folder has to be in _personal_ space of the user you execute the app as, your scenario of collecting photos from _personal_ spaces of two different users (available via the shared _album_) into a single folder in personal space of one of those users is not going to work currently. You can only export photos from shared space and personal space of the user you're executing the app as.

A workaround for now would be to:
1. User A exports into `/test1` in user A's personal space - physically this folder will be in `/homes/user_a/Photos/test1`. After this `/test1` will contain photos from the album that are in User A's personal space and in shared space.
2. User B exports into `/test2` in user B's personal space - `/homes/user_b/Photos/test2`. `/test2` now contains User B's personal space photos and shared space photos (which will be the same as shared space photos of User A).
3. User A moves photos "manually" (via Photos web client or File Station) from `/test1` to a target folder in _shared_ space, e.g. `/dest` - physically this folder will be in `/photo/dest`.
4. User B moves photos from `/test2` to the same target folder in shared space.

The code is currently communicating with **Synology Photos API** only, to make it copy to an arbitrary folder on the NAS would require it to use **File Station API** most likely, I'm not saying it's impossible but it would be much more difficult to implement because Photos uses its own internal IDs for files it manages, which is probably different from File Station IDs or paths - not sure as I don't have experience with File Station API.

**Comment by Caleb9** [comment]
I might think of making it possible to use shared space folder as export destination in the future though :)

**Comment by grandmastermarco** [comment]
Thank you so much once again for the very detailed explanation. I tought that i would be able to export to my normal Synology NAS folder with the --export option. But it makes sence that it is not possibleaccording to your explanation.
I was finally able to implement my usecase with your script. I used the --list command and then wrote a custom bash script to export those listed folders into a seperate directory.
